### ISSUE TITLE
Can not get notmuch-abook to work

### ISSUE THREAD

**Issue by rubdos** [imain/notmuch-vim#20]
Hi,

I'm trying to get https://github.com/guyzmo/notmuch-abook to work for e-mail address autocompletions, but it seems that it doesn't want to work with this fork.

[This line](https://github.com/guyzmo/notmuch-abook/blob/master/plugin/notmuch_abook.vim#L66) says that `filetype` should be `mail`, which is `notmuch-compose` by default.

Even if I set filetype to mail, notmuch_abook doesn't recognize me typing a name in the To: field. I can do lookups using `python .vim/bundle/notmuch-abook/pylibs/notmuch_abook.py lookup`

Is this a problem of notmuch-vim or one of notmuch_abook? Also: what can I supply to debug this?

**Comment by ff2000** [comment]
AFAICS notmuch-abook vim plugin is generic, it's not designed specifically for notmuch-vim frontend. Many console mail clients rely on an external editor for composing mail, and vim seems to be quite preferred - probably because the standard notmuch frontend is written for emacs, so most emacs users will use that directly ;) Some of those clients are bower, ner and alot - they all spawn vim, and that will use "mail" filetype.
You should be able to make notmuch-abook work if you replace "mail" by "notmuch-compose" in the augroup you linked to. Or add two new lines for ft "notmuch-compose" - if it works the author of notmuch-abook might be happy if he gets a pull request :)

**Comment by rubdos** [comment]
Okay, cool!

I'll issue a PR over there. Thanks for your assistance, it works. Main problem apparently was than I'm used to YouCompleteMe (the vim plugin) which automagically opens up the autocomplete. Didn't know I had to Ctrl-X Ctrl-U.

**Comment by rubdos** [comment]
So, I'll close this for now. Thank you!

**Comment by guyzmo** [comment]
for the note, I've coded `notmuch-abook` because I'm using `mutt-kz` :-) Because imho, vim is the best text editor, so I don't want it to be the best MUA ;-)

**Comment by ff2000** [comment]
@guyzmo AFAICS notmuch-compose is only because of the help text on top, which basically describes how to send or abort sending and how to attach files. I personally never liked it, but it was there from the beginning (see the files in "vim"-folder in the official notmuch release). I think there is plenty of documentation and people have to read it in any case, but I am neither the orginal author of the vim plugin nor the owner of this repo/fork, so I hesitate over removing the comment and the extra filetype.

**Comment by guyzmo** [comment]
ok, so that's technological debt ;-)

anyway, @rubdos's changeset has been merged, and now it'll support `notmuch-compose` as well :-)
